name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================
      - name: Build artifacts
        run: |
            # These are some amazing artifacts.
            echo "artifact1" > artifact1
            echo "artifact2" > artifact2

      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #         as shown below. Update the sha256 sum arguments
      #         to include all binaries that you generate
      #         provenance for.
      #
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          # List the artifacts the provenance will refer to.
          files=$(ls artifact*)
          # Generate the subjects (base64 encoded).
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    steps:
      - name: Set up environment
        run: |
          # Optional: Set any necessary environment variables here.
          echo "Setting up environment..."

      - name: Fetch Rekor public keys
        run: |
          # Fetch and display the Rekor public keys
          curl -L https://rekor.sigstore.dev/api/v1/log/publicKey -o rekor.pub
          echo "Rekor public key:"
          cat rekor.pub
          echo "Public key fetched and displayed."

      - name: Run SLSA verification
        run: |
          # Perform TUF client update with verbose logging
          tuf-client update --verbose || echo "TUF client update failed."
          
          # Run SLSA verifier with fetched Rekor public key
          slsa-verifier verify --rekor-key rekor.pub || echo "SLSA verification failed."

    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release
